import { Mine, InspectionData, ChecklistItem, AlertItem, User } from "../types";

export const MOCK_USER: User = {
  id: "usr-tech-102",
  name: "Inspector Amit Sharma",
  email: "amit.sharma@coalguard.gov.in",
  role: "SAFETY_INSPECTOR",
  assignedMineId: "mine-jharia-04",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
};

export const MOCK_MINES: Mine[] = [
  {
    id: "mine-jharia-04",
    name: "Jharia Block 4 Open Pit",
    code: "CG-JH-004",
    location: "Dhanbad, Jharkhand",
    latitude: 23.7957,
    longitude: 86.4304,
    status: "ACTIVE",
    safetyScore: 94.2,
    riskIndex: "LOW",
    activeWorkers: 342,
    dgmsZone: "Zone 1 - East",
  },
  {
    id: "mine-korba-02",
    name: "Korba South Pit",
    code: "CG-CG-002",
    location: "Korba, Chhattisgarh",
    latitude: 22.3595,
    longitude: 82.7501,
    status: "WARNING",
    safetyScore: 81.5,
    riskIndex: "HIGH",
    activeWorkers: 512,
    dgmsZone: "Zone 2 - South",
  },
  {
    id: "mine-singrauli-12",
    name: "Singrauli North Quarry",
    code: "CG-MP-012",
    location: "Singrauli, Madhya Pradesh",
    latitude: 24.1982,
    longitude: 82.6698,
    status: "CRITICAL",
    safetyScore: 72.0,
    riskIndex: "CRITICAL",
    activeWorkers: 280,
    dgmsZone: "Zone 3 - Central",
  },
  {
    id: "mine-talcher-08",
    name: "Talcher Deep Seam Mine",
    code: "CG-OR-008",
    location: "Angul, Odisha",
    latitude: 20.9500,
    longitude: 85.2300,
    status: "ACTIVE",
    safetyScore: 91.0,
    riskIndex: "LOW",
    activeWorkers: 410,
    dgmsZone: "Zone 4 - East Central",
  },
];

export const INITIAL_CHECKLIST: ChecklistItem[] = [
  {
    id: "chk-01",
    category: "Bench & Slope Stability",
    title: "Bench Angle & Height Ratio",
    description: "Verify slope bench angle does not exceed 45 degrees as mandated by DGMS Circular 04.",
    dgmsClause: "DGMS Reg. 106(1)",
    status: "COMPLIANT",
    remarks: "Slope angle measured at 41 degrees.",
  },
  {
    id: "chk-02",
    category: "Bench & Slope Stability",
    title: "Tension Crack Inspection",
    description: "Inspect top crest for tension cracks or rockfall hazards near Bench 3.",
    dgmsClause: "DGMS Reg. 106(3)",
    status: "NON_COMPLIANT",
    remarks: "Minor tension crack observed near Bench 3 crest.",
  },
  {
    id: "chk-03",
    category: "Gas & Environmental",
    title: "Methane Gas Detector Sweep",
    description: "Check underground shaft/seam for CH4 concentration below 1.25% VOL threshold.",
    dgmsClause: "DGMS Reg. 132",
    status: "COMPLIANT",
    remarks: "CH4 reading 0.35% VOL (Normal).",
  },
  {
    id: "chk-04",
    category: "Haul Road Safety",
    title: "Berm Height & Warning Signs",
    description: "Verify continuous safety berm height of minimum 1.5 meters along haul roads.",
    dgmsClause: "DGMS Circular 02/2021",
    status: "COMPLIANT",
    remarks: "Berm height 1.8m maintained.",
  },
  {
    id: "chk-05",
    category: "Heavy Equipment",
    title: "Dumper Proximity & Alarm Systems",
    description: "Inspect reverse audio-visual alarms and radar sensor on heavy dumper trucks.",
    dgmsClause: "DGMS Reg. 98",
    status: "COMPLIANT",
    remarks: "Alarms functioning on Dumper #14 & #18.",
  },
  {
    id: "chk-06",
    category: "Personal Protective Equipment",
    title: "Worker PPE Verification",
    description: "Ensure all miners in pit area wear reflective vests, safety helmets, and dust masks.",
    dgmsClause: "DGMS Safety Act Sec. 18",
    status: "COMPLIANT",
    remarks: "100% compliance observed during shift.",
  },
];

export const MOCK_INSPECTIONS: InspectionData[] = [
  {
    id: "insp-9041",
    mineId: "mine-jharia-04",
    mineName: "Jharia Block 4 Open Pit",
    inspectorId: "usr-tech-102",
    inspectorName: "Inspector Amit Sharma",
    date: "2026-09-23T08:30:00Z",
    status: "PASSED",
    hazardScore: 14,
    location: {
      latitude: 23.7957,
      longitude: 86.4304,
      accuracy: 4.2,
      altitude: 184.3,
      timestamp: Date.now() - 86400000,
    },
    checklist: INITIAL_CHECKLIST,
    observations: [
      {
        id: "obs-101",
        category: "Bench Stability",
        title: "Normal Pit Slope Crest",
        description: "Routine slope crest check. No slumping or rock displacement found.",
        hazardDetected: false,
        severity: "LOW",
        photoIds: ["p-1"],
      },
    ],
    hazards: [],
    severity: "LOW",
    remarks: "Mine safety standards fully verified according to DGMS Zone 1 regulations.",
    photos: [
      {
        id: "p-1",
        uri: "https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?w=600",
        fileName: "bench_crest_01.jpg",
        timestamp: "2026-09-23 08:45 AM",
        caption: "Bench 3 slope angle measurement",
        hazardTag: "Normal",
      },
    ],
    createdAt: "2026-09-23T08:30:00Z",
    synced: true,
  },
  {
    id: "insp-9042",
    mineId: "mine-korba-02",
    mineName: "Korba South Pit",
    inspectorId: "usr-tech-102",
    inspectorName: "Inspector Amit Sharma",
    date: "2026-09-22T14:15:00Z",
    status: "FAILED",
    hazardScore: 78,
    location: {
      latitude: 22.3595,
      longitude: 82.7501,
      accuracy: 3.8,
      altitude: 210.5,
      timestamp: Date.now() - 172800000,
    },
    checklist: INITIAL_CHECKLIST,
    observations: [
      {
        id: "obs-201",
        category: "Slope Instability",
        title: "Tension Crack on West Wall",
        description: "Significant 2.5m tension crack along Bench 4 haul road edge. Immediate evacuation recommended.",
        hazardDetected: true,
        severity: "HIGH",
        photoIds: ["p-2"],
      },
    ],
    hazards: ["Bench Tension Crack", "Haul Road Erosion"],
    severity: "HIGH",
    remarks: "Flagged for immediate remediation by Mine Manager.",
    photos: [
      {
        id: "p-2",
        uri: "https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?w=600",
        fileName: "tension_crack_w4.jpg",
        timestamp: "2026-09-22 02:30 PM",
        caption: "Tension crack on Bench 4 crest",
        hazardTag: "Tension Crack",
      },
    ],
    createdAt: "2026-09-22T14:15:00Z",
    synced: true,
  },
];

export const MOCK_ALERTS: AlertItem[] = [
  {
    id: "alt-801",
    mineId: "mine-singrauli-12",
    mineName: "Singrauli North Quarry",
    severity: "CRITICAL",
    title: "Slope Instability Threshold Exceeded",
    description: "Laser sensor detected 8mm displacement in North Pit Wall.",
    timestamp: "10 mins ago",
    read: false,
  },
  {
    id: "alt-802",
    mineId: "mine-korba-02",
    mineName: "Korba South Pit",
    severity: "HIGH",
    title: "Methane Gas Level Warning",
    description: "Shaft B Sensor #02 CH4 reading spiked to 1.15% VOL.",
    timestamp: "42 mins ago",
    read: false,
  },
  {
    id: "alt-803",
    mineId: "mine-jharia-04",
    mineName: "Jharia Block 4 Open Pit",
    severity: "LOW",
    title: "Shift Inspection Reminder",
    description: "Scheduled evening safety inspection due at 04:00 PM.",
    timestamp: "2 hours ago",
    read: true,
  },
];
