import { useEffect, useState } from "react";
import { Download, RefreshCw, Upload, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { getMinesApi, getRecentEvidenceApi, uploadEvidenceApi } from "@/lib/api";

type Row = Record<string, unknown>;
const display = (value: unknown) => value === null || value === undefined || value === "" ? "—" : String(value);

export function DocumentsView() {
  const [items, setItems] = useState<Row[]>([]); const [mines, setMines] = useState<Row[]>([]);
  const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [uploadOpen, setUploadOpen] = useState(false);
  const load = async () => { setLoading(true); setError(null); try { const [evidence, liveMines] = await Promise.all([getRecentEvidenceApi(), getMinesApi()]); setItems(evidence); setMines(liveMines); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load evidence."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h2 className="font-display text-2xl font-bold tracking-tight">Evidence Repository</h2><p className="text-sm text-muted-foreground">Satya Proof image evidence available in your permitted mine scope.</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => void load()} disabled={loading} className="gap-2"><RefreshCw className="size-4" /> Refresh</Button><Button size="sm" onClick={() => setUploadOpen(true)} className="gap-2"><Upload className="size-4" /> Upload evidence</Button></div></div>
    {error && <div role="alert" className="rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{error}</div>}
    <div className="dashboard-card overflow-hidden"><div className="overflow-x-auto"><table className="dashboard-table min-w-full"><thead><tr><th>ID</th><th>Mine</th><th>Trust score</th><th>Flags</th><th>Captured</th><th>File</th></tr></thead><tbody>{loading ? <tr><td colSpan={6} className="p-6 text-center text-muted-foreground">Loading evidence…</td></tr> : items.length === 0 ? <tr><td colSpan={6} className="p-6 text-center text-muted-foreground">No evidence is available in this scope.</td></tr> : items.map((item) => <tr key={display(item.id)}><td className="font-mono text-xs font-bold text-primary">#{display(item.id)}</td><td>{display(item.mine_name ?? item.mine_id)}</td><td><span className="font-semibold">{display(item.trust_score)}</span>/100</td><td className="max-w-48 truncate text-xs text-muted-foreground">{Array.isArray(item.flags) && item.flags.length ? item.flags.join(", ") : "None"}</td><td className="text-xs text-muted-foreground">{item.created_at ? new Date(String(item.created_at)).toLocaleString() : "—"}</td><td>{item.url ? <a className="inline-flex items-center gap-1 text-xs font-medium text-primary hover:underline" href={String(item.url)} target="_blank" rel="noreferrer"><Download className="size-3" /> Open</a> : "—"}</td></tr>)}</tbody></table></div></div>
    {uploadOpen && <UploadDialog mines={mines} close={() => setUploadOpen(false)} refresh={load} setError={setError} />}
  </div>;
}
function UploadDialog({ mines, close, refresh, setError }: { mines: Row[]; close: () => void; refresh: () => Promise<void>; setError: (message: string | null) => void }) {
  const [file, setFile] = useState<File | null>(null); const [mineId, setMineId] = useState(""); const [submitting, setSubmitting] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!file || !mineId) { setMessage("Choose a photo and mine site."); return; } setSubmitting(true); setMessage(null); try { await uploadEvidenceApi(file, Number(mineId), { device_time: new Date().toISOString() }); await refresh(); close(); } catch (err) { const detail = err instanceof Error ? err.message : "Evidence upload failed."; setMessage(detail); setError(detail); } finally { setSubmitting(false); } };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4 backdrop-blur-sm"><section role="dialog" aria-modal="true" className="dashboard-card w-full max-w-lg bg-card p-6 shadow-2xl"><div className="flex items-center justify-between border-b pb-3"><div><h3 className="font-display text-lg font-bold">Upload photo evidence</h3><p className="text-xs text-muted-foreground">JPEG, PNG, or WebP only. The server calculates the trust score.</p></div><Button variant="ghost" size="icon" onClick={close}><X className="size-4" /></Button></div><form className="mt-4 space-y-4" onSubmit={(event) => void submit(event)}><label className="block text-sm font-medium">Mine site<select required value={mineId} onChange={(event) => setMineId(event.target.value)} className="mt-1 w-full rounded-md border bg-background p-2 text-sm"><option value="">Select a permitted mine</option>{mines.map((mine) => <option key={display(mine.id)} value={display(mine.id)}>{display(mine.name)}</option>)}</select></label><label className="block text-sm font-medium">Photo<input required accept="image/jpeg,image/png,image/webp" type="file" onChange={(event) => setFile(event.target.files?.[0] ?? null)} className="mt-1 block w-full text-sm" /></label>{message && <p role="alert" className="text-sm text-destructive">{message}</p>}<div className="flex justify-end gap-2 border-t pt-4"><Button type="button" variant="outline" onClick={close}>Cancel</Button><Button disabled={submitting} type="submit">{submitting ? "Uploading…" : "Upload & check"}</Button></div></form></section></div>;
}
