import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Eye, MapPin, Mountain, RefreshCw, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { getMineDetailApi, getMinesApi } from "@/lib/api";

type Mine = Record<string, unknown>;
const text = (value: unknown) => value === null || value === undefined || value === "" ? "—" : String(value);
const riskTone = (risk: unknown) => {
  const level = String((risk as Record<string, unknown> | undefined)?.level ?? risk ?? "medium").toLowerCase();
  return level === "high" || level === "critical" ? "status-critical" : level === "low" ? "status-low" : "status-medium";
};

export function MinesView() {
  const [mines, setMines] = useState<Mine[]>([]);
  const [selected, setSelected] = useState<Mine | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [query, setQuery] = useState("");
  const load = async () => { setLoading(true); setError(null); try { setMines(await getMinesApi()); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load mines."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const visible = useMemo(() => mines.filter((mine) => [mine.name, mine.code, mine.area, mine.subsidiary, mine.manager_name].some((value) => text(value).toLowerCase().includes(query.toLowerCase()))), [mines, query]);
  const openDetail = async (mine: Mine) => { setSelected(mine); try { setSelected(await getMineDetailApi(Number(mine.id))); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load mine details."); } };
  const attention = mines.filter((mine) => Number(mine.overdue_tasks ?? 0) > 0 || Number(mine.open_capas ?? 0) > 0).length;
  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h2 className="font-display text-2xl font-bold tracking-tight">Mine Sites Directory</h2><p className="text-sm text-muted-foreground">Live mine, compliance, and risk information from the command backend.</p></div><Button variant="outline" size="sm" onClick={() => void load()} disabled={loading} className="gap-2"><RefreshCw className="size-4" /> Refresh</Button></div>
    <div className="grid gap-3 sm:grid-cols-3"><Metric label="Visible mine sites" value={mines.length} icon={<Mountain className="size-4 text-primary" />} /><Metric label="Needs attention" value={attention} icon={<AlertTriangle className="size-4 text-amber-500" />} /><Metric label="Average compliance" value={mines.length ? `${(mines.reduce((sum, mine) => sum + Number(mine.compliance_pct ?? 0), 0) / mines.length).toFixed(1)}%` : "—"} icon={<Users className="size-4 text-emerald-500" />} /></div>
    <div className="rounded-lg border bg-card p-4"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search mine, code, area, subsidiary or manager…" className="w-full rounded-md border bg-background px-3 py-2 text-sm outline-none focus:border-primary" /></div>
    {error && <Notice message={error} retry={load} />}
    {loading ? <p className="text-sm text-muted-foreground">Loading mine directory…</p> : visible.length === 0 ? <p className="rounded-lg border p-6 text-sm text-muted-foreground">No mines match this search in your permitted scope.</p> : <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{visible.map((mine) => { const risk = mine.risk as Record<string, unknown> | undefined; return <article key={text(mine.id)} className="dashboard-card flex flex-col p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{text(mine.code)}</p><h3 className="font-display text-lg font-bold">{text(mine.name)}</h3><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><MapPin className="size-3" /> {text(mine.area)}, {text(mine.subsidiary)}</p></div><span className={`status-badge ${riskTone(risk)}`}>{text(risk?.level ?? "unknown")} risk</span></div><div className="mt-4 grid grid-cols-2 gap-3 border-y py-3 text-xs"><Data label="Type" value={text(mine.mine_type)} /><Data label="Compliance" value={`${text(mine.compliance_pct)}%`} /><Data label="Overdue tasks" value={text(mine.overdue_tasks)} /><Data label="Open CAPAs" value={text(mine.open_capas)} /></div><div className="mt-4 flex justify-between gap-2"><span className="text-xs text-muted-foreground">Manager: {text(mine.manager_name)}</span><Button size="sm" variant="outline" onClick={() => void openDetail(mine)} className="gap-1"><Eye className="size-3" /> Details</Button></div></article>; })}</div>}
    {selected && <MineDialog mine={selected} close={() => setSelected(null)} />}
  </div>;
}
function Metric({ label, value, icon }: { label: string; value: string | number; icon: React.ReactNode }) { return <div className="dashboard-card p-4"><div className="flex items-center justify-between text-muted-foreground"><span className="text-xs font-semibold uppercase tracking-wider">{label}</span>{icon}</div><p className="mt-2 font-display text-3xl font-bold">{value}</p></div>; }
function Data({ label, value }: { label: string; value: string }) { return <div><p className="text-muted-foreground">{label}</p><p className="font-semibold">{value}</p></div>; }
function Notice({ message, retry }: { message: string; retry: () => Promise<void> }) { return <div role="alert" className="flex items-center justify-between gap-3 rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive"><span>{message}</span><Button variant="outline" size="sm" onClick={() => void retry()}>Retry</Button></div>; }
function MineDialog({ mine, close }: { mine: Mine; close: () => void }) { const risk = mine.risk as Record<string, unknown> | undefined; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4 backdrop-blur-sm"><section role="dialog" aria-modal="true" className="dashboard-card max-h-[90vh] w-full max-w-2xl overflow-y-auto bg-card p-6 shadow-2xl"><div className="flex items-start justify-between border-b pb-4"><div><p className="text-xs font-bold uppercase text-muted-foreground">{text(mine.code)}</p><h2 className="font-display text-xl font-bold">{text(mine.name)}</h2><p className="text-xs text-muted-foreground">{text(mine.area)} · {text(mine.mine_type)}</p></div><Button variant="ghost" size="icon" onClick={close}><X className="size-4" /></Button></div><div className="mt-5 grid grid-cols-2 gap-4 text-sm md:grid-cols-4"><Data label="Compliance" value={`${text(mine.compliance_pct)}%`} /><Data label="Open CAPAs" value={text(mine.open_capas)} /><Data label="Risk" value={text(risk?.level)} /><Data label="Risk source" value={text(risk?.source)} /></div><div className="mt-5 rounded-lg border p-4 text-sm"><p className="font-semibold">Operational details</p><dl className="mt-3 grid gap-3 sm:grid-cols-2"><Data label="Manager" value={text(mine.manager_name)} /><Data label="Coordinates" value={`${text(mine.center_lat)}, ${text(mine.center_lng)}`} /><Data label="Overdue tasks" value={text(mine.overdue_tasks)} /><Data label="Profile filled" value={mine.profile_filled ? "Yes" : "No"} /></dl></div><div className="mt-5 flex justify-end"><Button variant="outline" onClick={close}>Close</Button></div></section></div>; }
