import { useState } from "react";
import {
  FileBarChart,
  Download,
  Plus,
  Search,
  FileText,
  Calendar,
  Sparkles,
  CheckCircle,
  X,
  Printer,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const reportArchives = [
  {
    id: "REP-2026-09",
    title: "DGMS Monthly Statutory Safety & Compliance Dossier (Sep 2026)",
    mine: "All Coalfields (Aggregate)",
    author: "System AI / Er. Rajesh Kumar",
    date: "22 Sep 2026",
    size: "18.4 MB",
    format: "PDF",
    status: "Generated",
  },
  {
    id: "REP-2026-08",
    title: "Quarterly Highwall Slope Radar Displacement Audit",
    mine: "Kusunda Opencast Mine",
    author: "Geospatial AI Engine",
    date: "15 Sep 2026",
    size: "8.2 MB",
    format: "PDF",
    status: "Generated",
  },
  {
    id: "REP-2026-07",
    title: "Environmental MoEFCC Air & Water Quality Compliance Matrix",
    mine: "Jharia & Kusunda Mines",
    author: "Er. Sneha Das",
    date: "01 Sep 2026",
    size: "5.6 MB",
    format: "XLSX",
    status: "Generated",
  },
  {
    id: "REP-2026-06",
    title: "Underground Methane (CH4) Sensor Telemetry Audit Log",
    mine: "Jharia Underground Coal Mine",
    author: "IoT Sensor Pipeline",
    date: "28 Aug 2026",
    size: "14.1 MB",
    format: "CSV",
    status: "Generated",
  },
];

const templates = [
  {
    title: "DGMS Form IV Monthly Dossier",
    desc: "Comprehensive safety, gas readings, workforce medicals, and accident log for DGMS submission.",
    icon: FileText,
  },
  {
    title: "Slope Stability & Radar Summary",
    desc: "InSAR satellite radar data, micro-displacement heatmaps, and highwall bench angle analysis.",
    icon: FileBarChart,
  },
  {
    title: "Environmental NOC & Air Quality",
    desc: "PM10, PM2.5, effluent discharge water testing, and noise emission log sheets.",
    icon: Sparkles,
  },
];

export function ReportsView() {
  const [isGenerateModalOpen, setIsGenerateModalOpen] = useState(false);

  return (
    <div className="space-y-6">
      {/* Top Header */}
      <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center">
        <div>
          <h2 className="font-display text-2xl font-bold tracking-tight">Analytics & Report Generator</h2>
          <p className="text-sm text-muted-foreground">
            Generate statutory DGMS dossiers, environmental audits, slope analytics, and custom CSV data exports.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button onClick={() => setIsGenerateModalOpen(true)} className="gap-2">
            <Plus className="size-4" /> Generate Custom Report
          </Button>
        </div>
      </div>

      {/* Pre-Built Report Templates */}
      <div>
        <h3 className="font-display text-base font-bold mb-3">Pre-Configured Report Templates</h3>
        <div className="grid gap-4 md:grid-cols-3">
          {templates.map((tpl) => (
            <div key={tpl.title} className="dashboard-card p-5 flex flex-col justify-between hover:border-primary/50 transition-all">
              <div>
                <tpl.icon className="size-8 text-primary mb-3" />
                <h4 className="font-display text-base font-bold">{tpl.title}</h4>
                <p className="mt-1 text-xs text-muted-foreground leading-relaxed">{tpl.desc}</p>
              </div>
              <Button size="sm" variant="outline" className="mt-4 gap-2 text-xs" onClick={() => setIsGenerateModalOpen(true)}>
                <Printer className="size-3" /> Quick Generate
              </Button>
            </div>
          ))}
        </div>
      </div>

      {/* Generated Archive Table */}
      <div className="dashboard-card overflow-hidden">
        <div className="flex items-center justify-between border-b p-4">
          <h3 className="font-display text-base font-bold">Generated Reports Archive</h3>
          <span className="text-xs text-muted-foreground">Showing 4 recent reports</span>
        </div>
        <div className="overflow-x-auto">
          <table className="dashboard-table min-w-full">
            <thead>
              <tr>
                <th>Report ID</th>
                <th>Report Title</th>
                <th>Target Mine Site</th>
                <th>Generated By</th>
                <th>Date</th>
                <th>Size</th>
                <th>Format</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {reportArchives.map((rep) => (
                <tr key={rep.id} className="hover:bg-muted/30">
                  <td className="font-mono text-xs font-bold text-primary">{rep.id}</td>
                  <td className="font-semibold text-foreground">{rep.title}</td>
                  <td className="text-xs text-muted-foreground">{rep.mine}</td>
                  <td className="text-xs text-muted-foreground">{rep.author}</td>
                  <td className="text-xs text-muted-foreground">{rep.date}</td>
                  <td className="text-xs font-mono">{rep.size}</td>
                  <td>
                    <span className="text-xs font-bold uppercase text-primary">{rep.format}</span>
                  </td>
                  <td>
                    <Button variant="ghost" size="sm" className="gap-1 text-xs">
                      <Download className="size-3" /> Download
                    </Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Generate Custom Report Modal */}
      {isGenerateModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4 backdrop-blur-sm">
          <div className="dashboard-card w-full max-w-lg bg-card p-6 shadow-2xl">
            <div className="flex items-center justify-between border-b pb-3">
              <h3 className="font-display text-lg font-bold">Generate Custom Report</h3>
              <Button variant="ghost" size="icon" onClick={() => setIsGenerateModalOpen(false)}>
                <X className="size-4" />
              </Button>
            </div>

            <form
              onSubmit={(e) => {
                e.preventDefault();
                alert("Generating report dossier in background... Download ready shortly!");
                setIsGenerateModalOpen(false);
              }}
              className="mt-4 space-y-4"
            >
              <div>
                <label className="block text-xs font-semibold text-muted-foreground mb-1">Report Title</label>
                <input
                  type="text"
                  required
                  placeholder="e.g. September Safety Audit Summary"
                  className="w-full rounded-md border bg-background p-2 text-sm outline-none focus:border-primary"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-semibold text-muted-foreground mb-1">Select Mine Site</label>
                  <select className="w-full rounded-md border bg-background p-2 text-sm outline-none focus:border-primary">
                    <option>All Coalfields (Aggregate)</option>
                    <option>Jharia Underground Coal Mine</option>
                    <option>Kusunda Opencast Mine</option>
                    <option>Moonidih Shaft & Washery</option>
                  </select>
                </div>
                <div>
                  <label className="block text-xs font-semibold text-muted-foreground mb-1">Export Format</label>
                  <select className="w-full rounded-md border bg-background p-2 text-sm outline-none focus:border-primary">
                    <option value="PDF">PDF Document</option>
                    <option value="XLSX">Excel Workbook (XLSX)</option>
                    <option value="CSV">CSV Raw Data</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-xs font-semibold text-muted-foreground mb-2">Sections to Include</label>
                <div className="space-y-2 text-xs">
                  <label className="flex items-center gap-2">
                    <input type="checkbox" defaultChecked className="accent-primary" /> DGMS Statutory Compliance Scores
                  </label>
                  <label className="flex items-center gap-2">
                    <input type="checkbox" defaultChecked className="accent-primary" /> InSAR Slope Displacement Heatmap
                  </label>
                  <label className="flex items-center gap-2">
                    <input type="checkbox" defaultChecked className="accent-primary" /> Gas & Methane Telemetry Charts
                  </label>
                  <label className="flex items-center gap-2">
                    <input type="checkbox" defaultChecked className="accent-primary" /> Incident & RCA Action Tracker
                  </label>
                </div>
              </div>

              <div className="flex justify-end gap-2 border-t pt-4">
                <Button type="button" variant="outline" onClick={() => setIsGenerateModalOpen(false)}>
                  Cancel
                </Button>
                <Button type="submit">Compile & Export</Button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
